service: cart-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  profile: aws_bolotov
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
      Resource: '*'
    - Effect: Allow
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: '*'
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_NAME: ${env:DB_NAME}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}

useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-prune-versions

custom:
  prune:
    automatic: true

package:
  exclude:
    - ./**
  include:
    - dist/**
    - node_modules/**

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: '{proxy+}'
          method: ANY
